### ISSUE TITLE
When you guess correctly, make the person's name a link to their directory profile

### ISSUE THREAD

**Issue by botwhytho** [jasonaowen/recurse-faces#32]
Quick way to learn a bit more about somebody else. Having that quick context and linking somebody's name and face with 'likes Ruby' from their profile/bio facilitates learning.

This should be a quick one as we already have all the information to do this. Somebody's profile has the format https://www.recurse.com/directory/[person ID]-[first name]-[last name].

This could be combined with #29 as the same React component needs to be modified on both. #29 requires some additional changes in React and on the SQL query side but changes are not that involved.

**Comment by jasonaowen** [comment]
The back end already includes the person ID in the API response, so the front end should have everything it needs to generate this link.
