### ISSUE TITLE
Better readablility for solution texts

### ISSUE THREAD

**Issue by blinry** [jasonaowen/recurse-faces#38]
Especially green text on grey background is hard to read for my eyes (but that might be my color vision deficiency speaking). Anyhow, I'd suggest putting a background behind the text, or adding a text-shadow.
![screenshot-2019-04-02_16:12:20](https://user-images.githubusercontent.com/81277/55433023-6881be00-5562-11e9-8313-eed00105b790.png)

**Comment by jasonaowen** [comment]
@blinry yes, it's hard for me to read, as well!
