### ISSUE TITLE
Allow full name

### ISSUE THREAD

**Issue by jasonaowen** [jasonaowen/recurse-faces#39]
If someone correctly guesses the full name of a person, count that as a success rather than an error because their full name is not the same as their first name.

**Comment by jasonaowen** [comment]
Thank you for the suggestion, @jaryncolbert!

**Comment by blinry** [comment]
Also, in some cases, parts of the first name already form a valid answer! In "Firstname (Alias) Lastname", for example, I'd allow "Alias", and for "Firstname Secondname Thirdname Lastname", "Firstname" is probably fine, too?

**Comment by jasonaowen** [comment]
Ah, you're right! Right now it's doing the very unsophisticated thing of just looking at the `first_name` field returned from the RC API. I'm not sure exactly what the behavior should be, but maybe something like `guess = first_name OR guess = full_name OR guess in full_name.strip('()').split(' ')` (pseudocode)?

**Comment by jasonaowen** [comment]
Saving the full name will need to be a change to the `update-data.py` script, as well as the database schema in `schema.sql`.
