### ISSUE TITLE
Add contributors file

### ISSUE THREAD

**Issue by jaryncolbert** [jasonaowen/recurse-faces#44]
Per @jasonaowen's suggestion, we should keep track of the lovely folks who have helped bring faces to where it is! We'd like to track anyone who has contributed via a PR, pairing help, code review, etc. 

From the initial logs, I was going to add @jasonaowen, @botwhytho, @fedeisas, @brainwane, @blinry, and myself. For the folks tagged here, do you have any objections to being credited by first and last name with a link to your Github profile? If so, is Github username preferred or is there another name by which you would like to be referenced?

Thanks for your contributions!

**Comment by brainwane** [comment]
Crediting me with first+last name and GitHub profile link is fine!

**Comment by blinry** [comment]
Full name + link to the GitHub profile is fine for me, as well! :) Thanks again for your work on this!
