### ISSUE TITLE
Include instructions for .env files 

### ISSUE THREAD

**Issue by jaryncolbert** [jasonaowen/recurse-faces#52]
@jasonaowen had the idea to simplify the Flask configuration by setting the environment variables in a `.env` file, possibly using the [python-dotenv](https://github.com/theskumar/python-dotenv) library.

Some of the variables, like `FLASK_APP` can be exposed, but others, like `RC_API_ACCESS_TOKEN` are private and should not be under version control.

**Comment by jasonaowen** [comment]
Ah neat, I hadn't heard of `python-dotenv` before. I look forward to seeing how it works in practice!

Some things I think you already know but want to post for those following along: it would be useful to have a `.env.template` file with placeholder values, instructions on copying it to `.env` and editing that, and to ignore the `.env` file in `.gitignore`.

Thanks for filing this, @jaryncolbert !
